### ISSUE TITLE
content store wrapped incompletely

### ISSUE THREAD

**Issue by PerseidMeteor** [goharbor/acceleration-service#163]
content store wrapped containerd Content Store. But unfortunately, if we use the `provider. contentStore()` method to obtain the store, it will call `db. contentStore()`, which is another layer of wrap on the `containerd content Store`.

Then the methods like Info(), Update() we called is not the the methods we wrapped in content store.

**Comment by Desiki-high** [comment]
We can wrap the content store in upper level to fix it.

**Comment by PerseidMeteor** [comment]
certainly ok
