### ISSUE TITLE
feature request: make daemon works as a systemd process

### ISSUE THREAD

**Issue by Desiki-high** [goharbor/acceleration-service#223]
Can we make `acceld` as a systemd application ? We can load the config file in `/etc/acceld/config.yaml`. cc @imeoer.

**Comment by imeoer** [comment]
Should be fine, sounds like we need a systemd service config like https://github.com/containerd/nydus-snapshotter/blob/main/misc/snapshotter/nydus-snapshotter.fusedev.service .
