### ISSUE TITLE
Multiple manifest handling

### ISSUE THREAD

**Issue by liubogithub** [goharbor/acceleration-service#28]
There might be multiple manifests within an image, and looks like `acceld` tries to convert every manifest in the manifest list of image index file.
https://github.com/goharbor/acceleration-service/blob/a77d7f67c8a0f45d229fb28659cbb63e253b0cf2/pkg/driver/nydus/nydus.go#L170

However, currently acceld only pulls the first manifest, as shown 
https://github.com/goharbor/acceleration-service/blob/a77d7f67c8a0f45d229fb28659cbb63e253b0cf2/pkg/content/content.go#L91

IIUC, we just need to convert once as all manifests are supposed to refer to the exact same content, what do you think?

**Comment by imeoer** [comment]
@liubogithub Thanks for the report, this is indeed a bug. The manifest for different platforms may refer to different content, so we need to do conversions for each manifest, but we should provide an option to convert only the platform the user cares about.
