### ISSUE TITLE
Can deamonless accelctl parse parameter directly?

### ISSUE THREAD

**Issue by MercyMM** [goharbor/acceleration-service#29]
Can the parameters of deamonless accelctl be passed directly on the
command line instead of through the configuration file?

For example, referring to the practice of crictl, the auth parameter
is made into the following form: 
`crictl pull --auth "xxxx" image-name
`

deamonless accelctl also adds a "--auth" parameter, and other
parameters are similar.

**Comment by Desiki-high** [comment]
`Acceleration-Service` is a general service to support image acceleration, and `accelctl` is mainly to manage acceleration service. The `accelctl convert` can do image conversion in one-time mode, but we don't recommend using `accelctl` alone.

If we need a better one-time conversion experience, why not use an image-specific conversion tool? Such as [nydusify](https://github.com/dragonflyoss/image-service/tree/master/contrib/nydusify) or `nerdctl image convert`.

**Comment by imeoer** [comment]
It may be possible to support reading registry auth from the docker config.

**Comment by Desiki-high** [comment]
> It may be possible to support reading registry auth from the docker config.

If we support reading registry auth from the docker config, other driver configs also need config file. See https://github.com/goharbor/acceleration-service/blob/main/pkg/config/config.go#L82C6-L82C19

**Comment by Desiki-high** [comment]
Anyway, support reading registry auth from the docker config is a good idea.
