### ISSUE TITLE
support remote cache for driver

### ISSUE THREAD

**Issue by imeoer** [goharbor/acceleration-service#7]
Image layers that have already been converted should be cached to avoid being converted twice to speed up acceleration.

We can implement an LRU hash table that records the relationship from the digest of the source image layer to the digest of 
acceleration image layer, and store that hash table at some location (for example image manifest).

**Comment by PerseidMeteor** [comment]
I am glad to undertake it. @imeoer

**Comment by imeoer** [comment]
Has been finished by @PerseidMeteor, thanks.
