### ISSUE TITLE
Enhance service robustness

### ISSUE THREAD

**Issue by imeoer** [goharbor/acceleration-service#8]
- Retry (network failed on pulling or pushing).
- Support Multi-platform source images.
- Worker concurrency limitation.
- And more...

**Comment by Desiki-high** [comment]
It seems we have support `Multi-platform source images` and `Worker concurrency limitation`. What status of this issue? @imeoer

**Comment by imeoer** [comment]
@Desiki-high Yes, it seems the retry should be also supported, let's close it.
